### ISSUE TITLE
Listening to homekit

### ISSUE THREAD

**Issue by khwerhahn** [brutella/hc#191]
Hi,

I was wondering if somebody has an example on how to connect to homekit and then get all devices and listen to them. Also if further devices are added, they should also be added. 

Thanks

**Comment by timoschilling** [comment]
That what you want isn't possible by this and any other HomeKit accessory lib. HomeKit didn't allow inter device communication. If you want to build an devise that acts based on values from another device you need to create an automatisation using the Apple Home or Shortcuts app. If you want to create an dashboard or logger you need to create an iOS or Mac (since Big Sur) app.

**Comment by khwerhahn** [comment]
So in other words: I need to know each device and create it "manually" with hc?

**Comment by timoschilling** [comment]
Sorry it still sounds like you have wrong understanding what this lib does and how HomeKit works. Can you explain the big picture of what you want to do?

**Comment by khwerhahn** [comment]
Seems so :-)

I would like to create a little app that I can deploy on a raspberry pi with a touch screen and install it around the house so that people can use it to interact with the smart home. So the app just needs to know which room it is in and shows the available devices.

**Comment by timoschilling** [comment]
That's not possible, only iOS/macOS apps can interact with HomeKit devices.

**Comment by khwerhahn** [comment]
Thanks for helping, even though it is a little disappointing :-)
